version: "3.4"

services:
  scrapyprojectdocker:
    image: scrapyprojectdocker
    container_name: scrapy-container
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    networks:
      - app-tier
    env_file:
      - ./.env
    command: tail -f /dev/null
  db:
    image: ubuntu/postgres:14-22.04_beta
    container_name: scrapy-postgres-container
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge
